About page styles, custom paragraph
DueProcessed/dueprocessed.com pull request #43
Opened 2020-11-27 19:44 UTC by abepeterkin

2020-12-01 20:18 UTC, lilianammmatos commented
@abepeterkin could you split up this PR a bit more (smaller commits)? If you could specifically separate out a commit for adding the plugin (without any other changes for the custom block) and another for all the generated files (i.e. anything that goes in `wp-content/themes`).

Would we need the PRO version of ACF to support this one list for the masthead?

2020-12-01 20:36 UTC, lilianammmatos requested changes
I think it might make sense to even split up the block paragraph from the masthead into separate PRs to cut down on the size/complexity of this one.

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/sass/base/elements/_headers.scss
> +	font-size: 2.8rem;
There's already a stylesheet for headers: `due-processed/sass/base/typography/_headings.scss`

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/pages/pages.css
> +  font-size: 2.8rem;
You should be using mixins and variables for fonts: `https://github.com/DueProcessed/dueprocessed.com/blob/master/due-processed/sass/abstracts/variables/_typography.scss`

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/pages/pages.css
> +  line-height: 30px;
You shouldn't need to define a `line-height`, the font mixins already include that.

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/sass/pages/about.scss
> +.page-id-7 {
Instead of targeting a specific ID, could we create a generic stylesheet for generic "pages" (e.g. about, privacy policy, submission)?

2020-12-01 20:36 UTC, lilianammmatos commented on wp-content/themes/due-processed/functions.php
> +function custom_paragraph_block_init() {
I created a generic way of adding theme blocks in my PR: https://github.com/DueProcessed/dueprocessed.com/pull/44/files#diff-b9987849342bc95752845b4fc1e11ee69cc3daf36ee5670023fa12353a76d45fR155

So there's just one script / stylesheet (`editor.js`, `editor.css`) to add to the editor page.

We should sync up!

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/functions.php
> +function crb_attach_theme_options() {
Whether we decide to go with Carbon or ACF, you should create separate PHP file in the `inc` directory for this custom logic and `require` into here to keep things organized.

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/page-about.php
> +			if ( comments_open() || get_comments_number() ) :
We can remove this comment section, we won't want to support comments on this page

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/block-styles/custom-paragraph.css
> +	background-color: #e3eff4;
You should use the color variables here: `due-processed/sass/abstracts/variables/_colors.scss`.

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/sass/components/masthead/_masthead.scss
> +	font-family: "Lora Regular", georgia, "Times New Roman", times, serif;
Use font-mixin (applies to whole file)

2020-12-01 20:36 UTC, lilianammmatos commented on due-processed/sass/components/masthead/_masthead.scss
> +	margin-bottom: 40px;
Use spacing variables from `due-processed/sass/abstracts/variables/_structure.scss`

2020-12-04 18:54 UTC, abepeterkin commented on due-processed/sass/components/masthead/_masthead.scss
> +	font-family: "Lora Regular", georgia, "Times New Roman", times, serif;
What's font-mixin? I can't find that

2020-12-04 18:56 UTC, abepeterkin commented on due-processed/block-styles/custom-paragraph.css
> +	background-color: #e3eff4;
This is a css file, not a sass file

2020-12-04 19:10 UTC, abepeterkin commented on due-processed/sass/components/masthead/_masthead.scss
> +	font-family: "Lora Regular", georgia, "Times New Roman", times, serif;
never mind I found them

2020-12-04 19:30 UTC, abepeterkin commented on due-processed/sass/pages/about.scss
> +.page-id-7 {
I'm not sure if that's actually possible, I know you can have specific php templates for various pages, but to my knowledge every page on the site ultimately shares the same styles.css file, right?

2020-12-04 22:07 UTC, lilianammmatos commented on due-processed/sass/pages/about.scss
> +.page-id-7 {
I didn't mean create a different css file, but if there was a generic class that we could use for pages instead of targeting the ID. For single post pages, there's a `.single-post` class that I'm targeting, is there something like a `.page` class we could target. Then any "pages" would get these styles versus having to create a unique `.scss` file for each page type.

2020-12-07 23:00 UTC, abepeterkin commented on wp-content/themes/due-processed/functions.php
> +function custom_paragraph_block_init() {
I just moved the scripts/styles into those files

2020-12-07 23:10 UTC, abepeterkin commented on due-processed/sass/pages/about.scss
> +.page-id-7 {
Oh I get what you're saying. Yeah there is a .page class we could target, but I wasn't sure we wanted every page to have this layout. "Featured Articles" looks pretty different in the specs, for example.

2020-12-10 19:53 UTC, abepeterkin commented
@lilianammmatos Mind taking another look?

2020-12-15 13:59 UTC, lilianammmatos commented on due-processed/inc/masthead.php
> +		->where( 'post_id', '=', '7' ) // 7 is the id of the about page
did you get a chance to look into whether we could target the article slug instead of the `id`?

2020-12-15 13:59 UTC, lilianammmatos commented on due-processed/sass/components/masthead/_masthead.scss
> +	background-color: #ccc;
```suggestion
	background: $color__custom-paragraph
```

2020-12-15 13:59 UTC, lilianammmatos commented on due-processed/block-styles/custom-paragraph.css
> +@font-face {
Why do we need this `font-face` declarations? This should already be defined in https://github.com/DueProcessed/dueprocessed.com/blob/master/due-processed/sass/abstracts/mixins/_typography.scss

2020-12-15 13:59 UTC, lilianammmatos commented on due-processed/editor/custom-paragraph.css
> +@font-face {
Similar question here re: why do we need these `font-face` declarations?

2020-12-15 13:59 UTC, lilianammmatos commented on due-processed/pages/about.css
> +.page-id-7 .site-main {
Hmm why is there a separate `about.css`? Shouldn't these styles get included in the main `styles.css`?

2020-12-15 18:35 UTC, abepeterkin commented on due-processed/inc/masthead.php
> +		->where( 'post_id', '=', '7' ) // 7 is the id of the about page
I don't think there is a way to target the article slug (there's no `page-about` class unfortunately). There is a `.page` class we could target, but then every page would have these styles.

2020-12-15 19:54 UTC, lilianammmatos commented on due-processed/page-about.php
> +	<main id="primary" class="site-main">
You could add a class here for about page and target that instead of targeting the page id in the stylesheet
```suggestion
	<main id="primary" class="site-main site-main-about">
```

2020-12-15 20:03 UTC, lilianammmatos commented on due-processed/inc/masthead.php
> +		->where( 'post_id', '=', '7' ) // 7 is the id of the about page
Could you target by `post_template`?
```suggestion
		->where( 'post_template', '=', 'page-about.php' ) // 7 is the id of the about page
```
Does that work? See [example](https://carbonfields.net/docs/guides-section-layout-2/?crb_version=2-2-0).

2020-12-16 22:04 UTC, abepeterkin commented on due-processed/inc/masthead.php
> +		->where( 'post_id', '=', '7' ) // 7 is the id of the about page
Yes that works! Thanks

2020-12-16 22:14 UTC, abepeterkin commented on due-processed/pages/about.css
> +.page-id-7 .site-main {
Sorry, this and custom-paragraph.css were old and not actually being used so I deleted them

2020-12-17 17:36 UTC, lilianammmatos commented on due-processed/block-styles/custom-paragraph.css
> +@font-face {
bump. why is this file needed

2020-12-17 17:37 UTC, lilianammmatos commented
@abepeterkin not seeing any changes to the PR. Did that merge of master wipe out your changes?

2020-12-17 17:57 UTC, abepeterkin commented
> @abepeterkin not seeing any changes to the PR. Did that merge of master wipe out your changes?

I have no clue what happened here. That merge of master happened BEFORE I merged the PR changes

2020-12-17 18:22 UTC, abepeterkin commented on due-processed/inc/masthead.php
> +		->where( 'post_id', '=', '7' ) // 7 is the id of the about page
I ended up just removing this check.

2020-12-26 22:42 UTC, lilianammmatos approved these changes
minor comments

2020-12-26 22:42 UTC, lilianammmatos commented on due-processed/sass/style.scss
> +@import "editor/custom-paragraph";
You shouldn't need to put this here. The `editor.scss` gets put on the editor page.

2020-12-26 22:42 UTC, lilianammmatos commented on due-processed/functions.php
> +add_action('init', 'custom_paragraph_block_init');
Where is `custom_paragraph_block_init` defined?

2021-01-02 20:10 UTC, abepeterkin commented on due-processed/sass/style.scss
> +@import "editor/custom-paragraph";
This is for normal pages, it's applying the same styles to both. I didn't want to have two identical sass files for it.

2021-01-02 20:15 UTC, abepeterkin commented on due-processed/functions.php
> +add_action('init', 'custom_paragraph_block_init');
I forgot to take this out, removed!

2021-01-02 20:15 UTC, merged

2021-01-04 15:20 UTC, lilianammmatos commented on due-processed/sass/style.scss
> +@import "editor/custom-paragraph";
@abepeterkin do we need the complex styling on the editor page though? I think we should have the editor just apply a blue background to the text and have these complex styles (i.e. 100% width and other positioning) live outside the editor dir.